spring.application.name: media-service


spring:
  profiles:
    active: prod
  config:
    import: "configserver:"

  cloud:
    config:
      uri: http://202.178.125.77:9999

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

